services:
  compextai-db:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - 5433:5432
    volumes:
      - compextai-db-data-2:/var/lib/postgresql/data
    networks:
      - compextai-network
    restart: always
  compextai-server:
    build:
      context: compextAI-server/
      dockerfile: Dockerfile
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_HOST=compextai-db
      - POSTGRES_PORT=5432
      - POSTGRES_SSL_MODE=disable
      - SERVER_PORT=8888
      - EXECUTOR_BASE_URL=http://compextai-executor:8889
    depends_on:
      - compextai-db
      - compextai-executor
    networks:
      - compextai-network
    ports:
      - 8899:8888
    restart: always
  compextai-executor:
    build:
      context: compextAI-executor/
      dockerfile: Dockerfile
    environment:
      - SERVER_PORT=8889
    networks:
      - compextai-network
    ports:
      - 8889:8889
    restart: always
volumes:
  compextai-db-data-2:

networks:
  compextai-network:
    driver: bridge
